function gen(){
    var femalefnames = ["Aaliyah","Aliyah","Alyssa","Alissa","Abbi","Abby","Abbey","Abigail","Addison","Ally","Ali","Aileen","Megan","Meg","Bianca","Becky","Becca","Belle","Bella","Beverly","Alexa","Nia","Amy","Calia","Kalia","Katelyn","Kaitlyn","Caitlyn","Sam","Sammy","Rose","Rosie","Jasmin","Yasmin","Tara","Tina","Trinity","Kayla","Marley","Dakota","Marcie","Lois","Adrianna","Denise","Candace","Cherri","Cherrie","Chelsea","Lindsey","Lindsay","Lyndsey","Christina","Emily","Emmly","Sierra","Lorey","Lori","Cori","Corie","Eileen","Arielle","Ariell","April","Brooke","Brooklyn","Kate","Rebecca","Laura","Jadyn","Daisy","Dee","Ella","Elisa","Elyssa","Nikki","Haylie","Hailey","Hallie","Heather"];
    var lnames = ["Smith","Jones","Taylor","Williams","Brown","Davies","Evans","Wilson","Thomas","Roberts","Johnson","Lewis","Walker","Thompson","Watson","Jackson","Cooper","Wright","Green","Greene","Harris","Harrison","Lee","Martin","Clarke","Clark","James","Morgan","Hughes","Edwards","Hill","Moore","Scott","Young","Morris","Turner","Carter","Phillips","Mitchell","Anderson","Adams","Campbell","Davis","Miller","Marshall","Bennett","Richardson","Richards","Robertson","Reynolds","Reid","Ellis","Palmer","Graham","Stewart","Holmes","Stevens","Stevenson","Andrews","Atkins","Adkins","Owens","Knight","Harvey","Berry","Harper","Brooks","Brooke","Lawson","Fletcher","Burns","Jordan","Hopkins","McMahon","McDonald","McMillan","Ambrose","Doyle","Cooke","Long","Lopez","Lynch","Hawkins","Tucker","Patterson","Howe","Daniels","Danielson","Howell","Finch","Bown","Browne","Jacobs","Bowen","Silva","Walsh","Walch","Griffin","Peak","Steele","Wyatt","Perkins","Osborn","Osburn","Osbourne","Vaughan","Gaughan","Johns","Connors","Rhodes","Lang","Laing","Lovell","Glenn","Melone","Malone","Gould","Townley","Bullock","Herbert","Britton","O'Donnell","O'Neil","O'Neal","Dowling","Maxon","Clifton","Cena","Ackerman","Knox","Gaynor","Ansley","Hernandez","Wise","Mann","Hoffman","McIntyre"];
    var femalefnamesa = Math.floor(Math.random() * femalefnames.length);
    var lnamesa = Math.floor(Math.random() * lnames.length);
    var femalefnamesb = femalefnames[femalefnamesa];
    var lnamesb = lnames[lnamesa];
    document.getElementById("femalename").innerHTML = femalefnamesb + " " + lnamesb;
}
